### ISSUE TITLE
stitch.exe -cleanup fails with 'not enough pixel data'

### ISSUE THREAD

**Issue by danielniccoli** [Dadido3/noita-mapcap#11]
```text
PS C:\Games\Noita\mods\noita-mapcap> .\bin\stitch\stitch.exe -cleanup 0.999 -input output
2022/07/16 14:54:46 Starting to read tile information at "output"
2022/07/16 14:54:47 Got 2592 tiles
2022/07/16 14:54:47 Total size of the possible output space is (-18816,-32128)-(18304,41856)
2022/07/16 14:54:47 Cleaning up 2592 tiles at (-18816,-32128)-(18304,41856)
10546 / 10585 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->] 99.63% 192 p/s ETA 0s2022/07/16 14:55:40 Couldn't get image: png: invalid format: not enough pixel data
panic: Couldn't get image: png: invalid format: not enough pixel data

goroutine 1 [running]:
log.Panic(0xc0001cbc38, 0x1, 0x1)
        C:/Users/travis/.gimme/versions/go1.15.3.windows.amd64/src/log/log.go:351 +0xb7
main.main()
        C:/Users/travis/gopath/src/github.com/Dadido3/noita-mapcap/bin/stitch/stitch.go:185 +0x77d
PS C:\Games\Noita\mods\noita-mapcap>
```

**Comment by Dadido3** [comment]
I think this happens due to a malformed PNG that was created during a crash. I changed the stitcher to just output an error message, so it will continue to stitch on these error.

Usually there is enough overlap from other images, so that a few missing images don't matter. I also added the filepath to the error message, so if there are blank areas due to malformed PNG files, you can always delete them manually, and rerun the capture for the deleted images.

**Comment by danielniccoli** [comment]
> Usually there is enough overlap from other images, so that a few missing images don't matter.

I have a different resolution size and grid, so that could not apply to my configuration. But with the more detailed error message, I can do a manual cleanup. Thanks!
