### ISSUE TITLE
Getting error when starting new game

### ISSUE THREAD

**Issue by Ismoh** [Dadido3/noita-mapcap#16]
Hey there, I just downloaded MapCap 2.2.0 and I am getting those errors:

```lua
Noita (Apr 23 2021) - 20220827-222431
-------------------------------------------
Error loading lua script - file doesn't exist: mods/noita-mapcap/files/libraries/mod_settings.lua
Error loading lua script - file doesn't exist: mods/noita-mapcap/files/libraries/mod_settings/init.lua
Error loading lua script - file doesn't exist: mods/noita-mapcap/files/libraries/coroutines/init.lua
Error loading lua script - file doesn't exist: mods/noita-mapcap/files/libraries/noita-api/camera/init.lua
Error loading lua script - file doesn't exist: data/scripts/lib/noita-api/camera.lua
```
Any idea how to fix this?

**Comment by Dadido3** [comment]
These errors are "normal" and don't cause any problems. (Or is the mod not working correctly?)

Some more details why these messages appear:

I override and/or emulate some standard lua functions that Nolla decided to remove or break. One of them is `require` which is needed to load libraries and other stuff.

What `require` does is to try to load libraries based on patterns in `package.path`, which means that it has to try to load script files from several locations. For some reason the function to load scripts (`loadfile`) does output error messages to the stdout. And there is no way to prevent that, as these messages are hardcoded into `loadfile` and circumvent any normal lua error handling.

I don't see any way around that (beside using the default `require` that can't load files from Noita's virtual filesystem).
The problem is only of cosmetic nature, and only exists in the dev version. So, 🤷.

**Comment by Ismoh** [comment]
Thanks for the fast reply!
Unfortunatelly mapcap mod isnt working.
There is the red text notification that says something like "error while loading mapcap".
Noita_dev.exe or Noita.exe doesnt matter.

Which additional info do you need?

**Comment by Dadido3** [comment]
- How did you install the mod? Is the folder of the mod named `noita-mapcap`?
- Can you give a full copy of the console from `noita_dev.exe`?

**Comment by Dadido3** [comment]
Have you solved the problem, or does it still not work?

**Comment by Ismoh** [comment]
I didn't find time yet to provide the entire log, but will do later or the next days.
I think it is also pretty customised problem, because I am working on a multiplayer mod and I already did a lot modding, but need somehow to capture the map with mapcap.

Would be awesome to find a solution!
Thanks for answering again!
I'll keep you updated!

**Comment by Dadido3** [comment]
Ok, the problem is most likely that `package.path` can or can not have a trailing semicolon as entry separator. My assumption was that it always has one, as the default `package.path` ends with a semicolon.

I corrected that part, it should now work in all cases.

I hope that it fixes this issue.

**Comment by Ismoh** [comment]
I downloaded the latest master and it's working fine!
![image](https://user-images.githubusercontent.com/12631485/187228031-0e51946e-e972-4528-af58-2f855e60cbde.png)
