### ISSUE TITLE
Keeps going on the loop now

### ISSUE THREAD

**Issue by EfremovSerg** [Dadido3/noita-mapcap#6]
When I was looking to capture map in noita dev build, this goes into an infinite loop:

Lua error: [string "mods/noita-mapcap-master/init.lua"]:10: attempt to call global 'wake_up_waiting_threads' (a nil value).

Running on the last update. I launch this program no problem a couple days ago.

**Comment by Dadido3** [comment]
It seem's they changed how coroutines work, i'll take a look soon

**Comment by Dadido3** [comment]
Ok, i tested the mod and everything works as expected. Then i noticed that you have installed the mod inside `noita-mapcap-master` instead of `noita-mapcap`.

I'll close this issue as there is no bug. You just have to install a [release](https://github.com/Dadido3/noita-mapcap/releases/latest), and unpack it into the correctly named directory (`.../Noita/mods/noita-mapcap/mod.xml`).

**Comment by Dadido3** [comment]
If there is still some issue related to this, feel free to write here.
